export const BASE_URL = ''
export const USERS_URL = '/api/users'
export const CATEGORY_URL = '/api/category'
export const PRODUCT_URL = '/api/product'
export const UPLOAD_URL = '/api/uploads'
export const ORDER_URL = '/api/orders'
export const PAYPAL_URL = '/api/config/paypal'
export const imageURL = 'http://localhost:5000'